"""Add durable image and alt-text audit evidence and analyses.

Revision ID: 0011_image_alt_text_audit
Revises: 0010_internal_link_analysis
"""

# ruff: noqa: E501, I001, TC003

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0011_image_alt_text_audit"
down_revision: str | None = "0010_internal_link_analysis"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "image_audits",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("scope_snapshot_json", sa.Text(), nullable=False),
        sa.Column("configuration_json", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=40), nullable=False),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("image_occurrence_count", sa.Integer(), nullable=False),
        sa.Column("unique_image_count", sa.Integer(), nullable=False),
        sa.Column("valid_image_count", sa.Integer(), nullable=False),
        sa.Column("broken_image_count", sa.Integer(), nullable=False),
        sa.Column("redirecting_image_count", sa.Integer(), nullable=False),
        sa.Column("unverified_image_count", sa.Integer(), nullable=False),
        sa.Column("missing_alt_count", sa.Integer(), nullable=False),
        sa.Column("empty_alt_count", sa.Integer(), nullable=False),
        sa.Column("generic_alt_count", sa.Integer(), nullable=False),
        sa.Column("filename_alt_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_alt_count", sa.Integer(), nullable=False),
        sa.Column("missing_dimensions_count", sa.Integer(), nullable=False),
        sa.Column("loading_review_count", sa.Integer(), nullable=False),
        sa.Column("recommendation_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("audit_version", sa.String(length=64), nullable=False),
        sa.Column("evidence_version", sa.String(length=64), nullable=False),
        sa.Column("policy_version", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "state in ('accepted','claiming','building_inventory','resolving_resources','classifying_alt_text','analyzing_reuse','building_recommendations','completed','completed_with_warnings','failed','cancelled')",
            name="ck_image_audit_state",
        ),
        sa.CheckConstraint(
            "warning_count >= 0 and image_occurrence_count >= 0 and unique_image_count >= 0 and valid_image_count >= 0 and broken_image_count >= 0 and redirecting_image_count >= 0 and unverified_image_count >= 0 and missing_alt_count >= 0 and empty_alt_count >= 0 and generic_alt_count >= 0 and filename_alt_count >= 0 and duplicate_alt_count >= 0 and missing_dimensions_count >= 0 and loading_review_count >= 0 and recommendation_count >= 0",
            name="ck_image_audit_counts",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("audit_id"),
        sa.UniqueConstraint(
            "run_id", "configuration_json", name="uq_image_audit_run_configuration"
        ),
    )
    op.create_index(
        "ix_image_audit_run", "image_audits", ["run_id", "created_at", "audit_id"], unique=False
    )
    op.create_index(
        "ix_image_audit_state", "image_audits", ["state", "created_at", "audit_id"], unique=False
    )
    op.create_table(
        "crawl_image_evidence",
        sa.Column("image_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("source_evidence_id", sa.String(length=64), nullable=False),
        sa.Column("source_requested_url", sa.Text(), nullable=False),
        sa.Column("source_final_url", sa.Text(), nullable=True),
        sa.Column("source_url_identity", sa.String(length=64), nullable=False),
        sa.Column("source_discovery_sequence", sa.Integer(), nullable=False),
        sa.Column("source_crawl_depth", sa.Integer(), nullable=False),
        sa.Column("element_sequence", sa.Integer(), nullable=False),
        sa.Column("occurrence_sequence", sa.Integer(), nullable=False),
        sa.Column("element_type", sa.String(length=32), nullable=False),
        sa.Column("source_kind", sa.String(length=32), nullable=False),
        sa.Column("raw_src", sa.Text(), nullable=True),
        sa.Column("resolved_src", sa.Text(), nullable=True),
        sa.Column("image_identity", sa.String(length=64), nullable=True),
        sa.Column("raw_srcset", sa.Text(), nullable=True),
        sa.Column("srcset_candidates_json", sa.Text(), nullable=False),
        sa.Column("primary_candidate", sa.Text(), nullable=True),
        sa.Column("sizes", sa.Text(), nullable=True),
        sa.Column("alt_present", sa.Boolean(), nullable=False),
        sa.Column("alt_raw", sa.Text(), nullable=True),
        sa.Column("alt_normalized", sa.Text(), nullable=True),
        sa.Column("title_value", sa.Text(), nullable=True),
        sa.Column("width_value", sa.String(length=64), nullable=True),
        sa.Column("height_value", sa.String(length=64), nullable=True),
        sa.Column("loading_value", sa.String(length=32), nullable=True),
        sa.Column("decoding_value", sa.String(length=32), nullable=True),
        sa.Column("fetch_priority", sa.String(length=32), nullable=True),
        sa.Column("linked", sa.Boolean(), nullable=False),
        sa.Column("parent_link_url", sa.Text(), nullable=True),
        sa.Column("decorative_explicit", sa.Boolean(), nullable=False),
        sa.Column("role_value", sa.String(length=64), nullable=True),
        sa.Column("aria_hidden_value", sa.String(length=16), nullable=True),
        sa.Column("in_scope", sa.Boolean(), nullable=True),
        sa.Column("scope_reason_code", sa.String(length=64), nullable=True),
        sa.Column("source_scheme", sa.String(length=32), nullable=True),
        sa.Column("data_media_type", sa.String(length=128), nullable=True),
        sa.Column("data_byte_length_estimate", sa.Integer(), nullable=True),
        sa.Column("data_fingerprint", sa.String(length=24), nullable=True),
        sa.Column("unsupported_scheme", sa.Boolean(), nullable=False),
        sa.Column("parse_warning", sa.String(length=64), nullable=True),
        sa.Column("value_truncated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_version", sa.String(length=64), nullable=False),
        sa.CheckConstraint(
            "data_byte_length_estimate is null or data_byte_length_estimate >= 0",
            name="ck_crawl_image_data_length",
        ),
        sa.CheckConstraint(
            "source_discovery_sequence >= 0 and source_crawl_depth >= 0 and element_sequence >= 0 and occurrence_sequence >= 0",
            name="ck_crawl_image_sequences",
        ),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"], ["crawl_page_evidence.evidence_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("image_id"),
        sa.UniqueConstraint("run_id", "occurrence_sequence", name="uq_crawl_image_run_sequence"),
        sa.UniqueConstraint(
            "source_evidence_id", "element_sequence", name="uq_crawl_image_source_sequence"
        ),
    )
    op.create_index(
        "ix_crawl_image_identity",
        "crawl_image_evidence",
        ["run_id", "image_identity", "occurrence_sequence"],
        unique=False,
    )
    op.create_index(
        "ix_crawl_image_run_order",
        "crawl_image_evidence",
        ["run_id", "occurrence_sequence", "image_id"],
        unique=False,
    )
    op.create_index(
        "ix_crawl_image_scope",
        "crawl_image_evidence",
        ["run_id", "in_scope", "source_scheme"],
        unique=False,
    )
    op.create_index(
        "ix_crawl_image_source",
        "crawl_image_evidence",
        ["source_evidence_id", "element_sequence"],
        unique=False,
    )
    op.create_table(
        "image_audit_events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("event_type", sa.String(length=40), nullable=False),
        sa.Column("safe_reason_code", sa.String(length=128), nullable=True),
        sa.Column("affected_count", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.String(length=64), nullable=False),
        sa.CheckConstraint("affected_count >= 0", name="ck_image_audit_event_count"),
        sa.ForeignKeyConstraint(["audit_id"], ["image_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(
        "ix_image_audit_event_order", "image_audit_events", ["audit_id", "event_id"], unique=False
    )
    op.create_table(
        "image_audit_exports",
        sa.Column("export_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("export_format", sa.String(length=48), nullable=False),
        sa.Column("artifact_id", sa.String(length=64), nullable=True),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=16), nullable=False),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifact_records.artifact_id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["image_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("export_id"),
        sa.UniqueConstraint("audit_id", "export_format", name="uq_image_audit_export"),
    )
    op.create_table(
        "image_audit_resources",
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("image_identity", sa.String(length=64), nullable=False),
        sa.Column("representative_url", sa.Text(), nullable=True),
        sa.Column("scope_state", sa.String(length=32), nullable=False),
        sa.Column("fetch_state", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("status_class", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=256), nullable=True),
        sa.Column("redirect_state", sa.String(length=32), nullable=False),
        sa.Column("final_image_url", sa.Text(), nullable=True),
        sa.Column("response_byte_count", sa.Integer(), nullable=True),
        sa.Column("resource_state", sa.String(length=40), nullable=False),
        sa.Column("unique_source_page_count", sa.Integer(), nullable=False),
        sa.Column("total_occurrence_count", sa.Integer(), nullable=False),
        sa.Column("unique_alt_count", sa.Integer(), nullable=False),
        sa.Column("missing_alt_count", sa.Integer(), nullable=False),
        sa.Column("empty_alt_count", sa.Integer(), nullable=False),
        sa.Column("linked_occurrence_count", sa.Integer(), nullable=False),
        sa.Column("broken_occurrence_count", sa.Integer(), nullable=False),
        sa.Column("redirecting_occurrence_count", sa.Integer(), nullable=False),
        sa.Column("width_consistent", sa.Boolean(), nullable=False),
        sa.Column("height_consistent", sa.Boolean(), nullable=False),
        sa.Column("loading_distribution_json", sa.Text(), nullable=False),
        sa.Column("earliest_discovery_sequence", sa.Integer(), nullable=False),
        sa.Column("minimum_source_depth", sa.Integer(), nullable=False),
        sa.Column("maximum_source_depth", sa.Integer(), nullable=False),
        sa.Column("sitewide_state", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("resource_sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "http_status is null or (http_status >= 100 and http_status <= 599)",
            name="ck_image_resource_http_status",
        ),
        sa.CheckConstraint(
            "unique_source_page_count >= 0 and total_occurrence_count > 0 and unique_alt_count >= 0 and missing_alt_count >= 0 and empty_alt_count >= 0 and linked_occurrence_count >= 0 and broken_occurrence_count >= 0 and redirecting_occurrence_count >= 0 and earliest_discovery_sequence >= 0 and minimum_source_depth >= 0 and maximum_source_depth >= minimum_source_depth and resource_sequence >= 0",
            name="ck_image_resource_counts",
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["image_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("resource_id"),
        sa.UniqueConstraint("audit_id", "image_identity", name="uq_image_resource_identity"),
        sa.UniqueConstraint("audit_id", "resource_sequence", name="uq_image_resource_sequence"),
    )
    op.create_index(
        "ix_image_resource_filter",
        "image_audit_resources",
        ["audit_id", "resource_state", "severity", "sitewide_state"],
        unique=False,
    )
    op.create_index(
        "ix_image_resource_order",
        "image_audit_resources",
        ["audit_id", "resource_sequence", "resource_id"],
        unique=False,
    )
    op.create_table(
        "image_duplicate_groups",
        sa.Column("group_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("group_type", sa.String(length=48), nullable=False),
        sa.Column("group_identity", sa.String(length=64), nullable=False),
        sa.Column("representative_alt", sa.Text(), nullable=True),
        sa.Column("image_count", sa.Integer(), nullable=False),
        sa.Column("source_page_count", sa.Integer(), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("sample_images_json", sa.Text(), nullable=False),
        sa.Column("sample_pages_json", sa.Text(), nullable=False),
        sa.Column("group_sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "image_count > 0 and source_page_count > 0 and occurrence_count > 0 and group_sequence >= 0",
            name="ck_image_duplicate_counts",
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["image_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id"),
        sa.UniqueConstraint("audit_id", "group_sequence", name="uq_image_duplicate_sequence"),
        sa.UniqueConstraint(
            "audit_id", "group_type", "group_identity", name="uq_image_duplicate_group"
        ),
    )
    op.create_index(
        "ix_image_duplicate_filter",
        "image_duplicate_groups",
        ["audit_id", "group_type", "severity"],
        unique=False,
    )
    op.create_index(
        "ix_image_duplicate_order",
        "image_duplicate_groups",
        ["audit_id", "group_sequence", "group_id"],
        unique=False,
    )
    op.create_table(
        "image_page_summaries",
        sa.Column("page_summary_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("source_evidence_id", sa.String(length=64), nullable=False),
        sa.Column("source_page_url", sa.Text(), nullable=False),
        sa.Column("image_occurrence_count", sa.Integer(), nullable=False),
        sa.Column("unique_image_count", sa.Integer(), nullable=False),
        sa.Column("missing_alt_count", sa.Integer(), nullable=False),
        sa.Column("empty_alt_count", sa.Integer(), nullable=False),
        sa.Column("broken_image_count", sa.Integer(), nullable=False),
        sa.Column("redirecting_image_count", sa.Integer(), nullable=False),
        sa.Column("missing_dimensions_count", sa.Integer(), nullable=False),
        sa.Column("loading_review_count", sa.Integer(), nullable=False),
        sa.Column("generic_alt_count", sa.Integer(), nullable=False),
        sa.Column("filename_alt_count", sa.Integer(), nullable=False),
        sa.Column("duplicate_alt_count", sa.Integer(), nullable=False),
        sa.Column("external_image_count", sa.Integer(), nullable=False),
        sa.Column("data_image_count", sa.Integer(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("page_sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "image_occurrence_count >= 0 and unique_image_count >= 0 and missing_alt_count >= 0 and empty_alt_count >= 0 and broken_image_count >= 0 and redirecting_image_count >= 0 and missing_dimensions_count >= 0 and loading_review_count >= 0 and generic_alt_count >= 0 and filename_alt_count >= 0 and duplicate_alt_count >= 0 and external_image_count >= 0 and data_image_count >= 0 and page_sequence >= 0",
            name="ck_image_page_counts",
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["image_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"], ["crawl_page_evidence.evidence_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("page_summary_id"),
        sa.UniqueConstraint("audit_id", "page_sequence", name="uq_image_page_sequence"),
        sa.UniqueConstraint("audit_id", "source_evidence_id", name="uq_image_page_summary"),
    )
    op.create_index(
        "ix_image_page_filter",
        "image_page_summaries",
        ["audit_id", "severity", "missing_alt_count", "broken_image_count"],
        unique=False,
    )
    op.create_index(
        "ix_image_page_order",
        "image_page_summaries",
        ["audit_id", "page_sequence", "page_summary_id"],
        unique=False,
    )
    op.create_table(
        "image_occurrence_analyses",
        sa.Column("analysis_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("image_evidence_id", sa.String(length=64), nullable=False),
        sa.Column("source_evidence_id", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=False),
        sa.Column("source_page_url", sa.Text(), nullable=False),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("raw_src", sa.Text(), nullable=True),
        sa.Column("primary_candidate", sa.Text(), nullable=True),
        sa.Column("element_type", sa.String(length=32), nullable=False),
        sa.Column("alt_raw", sa.Text(), nullable=True),
        sa.Column("alt_normalized", sa.Text(), nullable=True),
        sa.Column("width_value", sa.String(length=64), nullable=True),
        sa.Column("height_value", sa.String(length=64), nullable=True),
        sa.Column("loading_value", sa.String(length=32), nullable=True),
        sa.Column("decoding_value", sa.String(length=32), nullable=True),
        sa.Column("fetch_priority", sa.String(length=32), nullable=True),
        sa.Column("alt_state", sa.String(length=48), nullable=False),
        sa.Column("dimension_state", sa.String(length=40), nullable=False),
        sa.Column("loading_state", sa.String(length=40), nullable=False),
        sa.Column("linked_image", sa.Boolean(), nullable=False),
        sa.Column("decorative", sa.Boolean(), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("primary_reason", sa.String(length=64), nullable=False),
        sa.Column("occurrence_sequence", sa.Integer(), nullable=False),
        sa.CheckConstraint("occurrence_sequence >= 0", name="ck_image_occurrence_sequence"),
        sa.ForeignKeyConstraint(["audit_id"], ["image_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["image_evidence_id"], ["crawl_image_evidence.image_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["image_audit_resources.resource_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"], ["crawl_page_evidence.evidence_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("analysis_id"),
        sa.UniqueConstraint("audit_id", "image_evidence_id", name="uq_image_occurrence_evidence"),
        sa.UniqueConstraint("audit_id", "occurrence_sequence", name="uq_image_occurrence_sequence"),
    )
    op.create_index(
        "ix_image_occurrence_filter",
        "image_occurrence_analyses",
        ["audit_id", "alt_state", "dimension_state", "loading_state", "severity"],
        unique=False,
    )
    op.create_index(
        "ix_image_occurrence_order",
        "image_occurrence_analyses",
        ["audit_id", "occurrence_sequence", "analysis_id"],
        unique=False,
    )
    op.create_index(
        "ix_image_occurrence_page",
        "image_occurrence_analyses",
        ["audit_id", "source_evidence_id", "occurrence_sequence"],
        unique=False,
    )
    op.create_table(
        "image_findings",
        sa.Column("finding_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("analysis_id", sa.String(length=64), nullable=True),
        sa.Column("page_summary_id", sa.String(length=64), nullable=True),
        sa.Column("duplicate_group_id", sa.String(length=64), nullable=True),
        sa.Column("stable_code", sa.String(length=64), nullable=False),
        sa.Column("finding_type", sa.String(length=32), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("safe_message", sa.String(length=512), nullable=False),
        sa.Column("context_json", sa.Text(), nullable=False),
        sa.Column("finding_sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["image_occurrence_analyses.analysis_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["image_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["duplicate_group_id"], ["image_duplicate_groups.group_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["page_summary_id"], ["image_page_summaries.page_summary_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["image_audit_resources.resource_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("finding_id"),
        sa.UniqueConstraint("audit_id", "finding_sequence", name="uq_image_finding_sequence"),
    )
    op.create_index(
        "ix_image_finding_filter",
        "image_findings",
        ["audit_id", "finding_type", "severity", "stable_code"],
        unique=False,
    )
    op.create_index(
        "ix_image_finding_order",
        "image_findings",
        ["audit_id", "finding_sequence", "finding_id"],
        unique=False,
    )
    op.create_table(
        "image_recommendations",
        sa.Column("recommendation_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("analysis_id", sa.String(length=64), nullable=True),
        sa.Column("resource_id", sa.String(length=64), nullable=True),
        sa.Column("source_page_url", sa.Text(), nullable=True),
        sa.Column("image_url", sa.Text(), nullable=True),
        sa.Column("image_identity", sa.String(length=64), nullable=True),
        sa.Column("action", sa.String(length=48), nullable=False),
        sa.Column("confidence", sa.String(length=16), nullable=False),
        sa.Column("severity", sa.String(length=16), nullable=False),
        sa.Column("reason_code", sa.String(length=64), nullable=False),
        sa.Column("human_review_state", sa.String(length=32), nullable=False),
        sa.Column("supporting_metrics_json", sa.Text(), nullable=False),
        sa.Column("recommendation_sequence", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_id"], ["image_occurrence_analyses.analysis_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["image_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["resource_id"], ["image_audit_resources.resource_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("recommendation_id"),
        sa.UniqueConstraint(
            "audit_id", "recommendation_sequence", name="uq_image_recommendation_sequence"
        ),
    )
    op.create_index(
        "ix_image_recommendation_filter",
        "image_recommendations",
        ["audit_id", "action", "confidence", "severity", "human_review_state"],
        unique=False,
    )
    op.create_index(
        "ix_image_recommendation_order",
        "image_recommendations",
        ["audit_id", "recommendation_sequence", "recommendation_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_image_recommendation_order", table_name="image_recommendations")
    op.drop_index("ix_image_recommendation_filter", table_name="image_recommendations")
    op.drop_table("image_recommendations")
    op.drop_index("ix_image_finding_order", table_name="image_findings")
    op.drop_index("ix_image_finding_filter", table_name="image_findings")
    op.drop_table("image_findings")
    op.drop_index("ix_image_occurrence_page", table_name="image_occurrence_analyses")
    op.drop_index("ix_image_occurrence_order", table_name="image_occurrence_analyses")
    op.drop_index("ix_image_occurrence_filter", table_name="image_occurrence_analyses")
    op.drop_table("image_occurrence_analyses")
    op.drop_index("ix_image_page_order", table_name="image_page_summaries")
    op.drop_index("ix_image_page_filter", table_name="image_page_summaries")
    op.drop_table("image_page_summaries")
    op.drop_index("ix_image_duplicate_order", table_name="image_duplicate_groups")
    op.drop_index("ix_image_duplicate_filter", table_name="image_duplicate_groups")
    op.drop_table("image_duplicate_groups")
    op.drop_index("ix_image_resource_order", table_name="image_audit_resources")
    op.drop_index("ix_image_resource_filter", table_name="image_audit_resources")
    op.drop_table("image_audit_resources")
    op.drop_table("image_audit_exports")
    op.drop_index("ix_image_audit_event_order", table_name="image_audit_events")
    op.drop_table("image_audit_events")
    op.drop_index("ix_crawl_image_source", table_name="crawl_image_evidence")
    op.drop_index("ix_crawl_image_scope", table_name="crawl_image_evidence")
    op.drop_index("ix_crawl_image_run_order", table_name="crawl_image_evidence")
    op.drop_index("ix_crawl_image_identity", table_name="crawl_image_evidence")
    op.drop_table("crawl_image_evidence")
    op.drop_index("ix_image_audit_state", table_name="image_audits")
    op.drop_index("ix_image_audit_run", table_name="image_audits")
    op.drop_table("image_audits")
    # ### end Alembic commands ###
