"""add structured data audit

Revision ID: 0012_structured_data_audit
Revises: 0011_image_alt_text_audit
"""

# ruff: noqa: TC003

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "0012_structured_data_audit"
down_revision: str | Sequence[str] | None = "0011_image_alt_text_audit"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "structured_data_audits",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("job_id", sa.String(length=40), nullable=False),
        sa.Column("configuration_json", sa.Text(), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("total_pages", sa.Integer(), nullable=False),
        sa.Column("total_blocks", sa.Integer(), nullable=False),
        sa.Column("total_entities", sa.Integer(), nullable=False),
        sa.Column("total_findings", sa.Integer(), nullable=False),
        sa.Column("warning_count", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("retention_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("audit_id"),
        sa.UniqueConstraint("run_id", "configuration_json", name="uq_structured_audit_run_config"),
    )
    op.create_table(
        "crawl_structured_data_evidence",
        sa.Column("block_id", sa.String(length=64), nullable=False),
        sa.Column("job_id", sa.String(length=40), nullable=False),
        sa.Column("run_id", sa.String(length=32), nullable=False),
        sa.Column("source_evidence_id", sa.String(length=64), nullable=False),
        sa.Column("source_requested_url", sa.Text(), nullable=False),
        sa.Column("source_final_url", sa.Text(), nullable=True),
        sa.Column("source_url_identity", sa.String(length=64), nullable=False),
        sa.Column("source_discovery_sequence", sa.Integer(), nullable=False),
        sa.Column("source_crawl_depth", sa.Integer(), nullable=False),
        sa.Column("element_sequence", sa.Integer(), nullable=False),
        sa.Column("occurrence_sequence", sa.Integer(), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("source_locator", sa.String(length=512), nullable=False),
        sa.Column("script_type", sa.String(length=128), nullable=True),
        sa.Column("raw_value", sa.Text(), nullable=False),
        sa.Column("raw_length", sa.Integer(), nullable=False),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("parse_error", sa.String(length=512), nullable=True),
        sa.Column("contexts_json", sa.Text(), nullable=False),
        sa.Column("types_json", sa.Text(), nullable=False),
        sa.Column("identifiers_json", sa.Text(), nullable=False),
        sa.Column("properties_json", sa.Text(), nullable=False),
        sa.Column("references_json", sa.Text(), nullable=False),
        sa.Column("raw_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("normalized_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("duplicate_keys_json", sa.Text(), nullable=False),
        sa.Column("diagnostics_json", sa.Text(), nullable=False),
        sa.Column("value_truncated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("evidence_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["job_id"], ["jobs.job_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["run_id"], ["runs.run_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["source_evidence_id"], ["crawl_page_evidence.evidence_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("block_id"),
        sa.UniqueConstraint(
            "run_id", "occurrence_sequence", name="uq_structured_evidence_run_sequence"
        ),
        sa.UniqueConstraint(
            "source_evidence_id", "element_sequence", name="uq_structured_evidence_source_sequence"
        ),
    )
    with op.batch_alter_table("crawl_structured_data_evidence", schema=None) as batch_op:
        batch_op.create_index(
            "ix_structured_evidence_run", ["run_id", "occurrence_sequence"], unique=False
        )

    op.create_table(
        "structured_data_blocks",
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("format", sa.String(length=32), nullable=False),
        sa.Column("parse_status", sa.String(length=32), nullable=False),
        sa.Column("types_json", sa.Text(), nullable=False),
        sa.Column("identifiers_json", sa.Text(), nullable=False),
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_blocks", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_blocks_audit_id"), ["audit_id"], unique=False
        )

    op.create_table(
        "structured_data_duplicate_groups",
        sa.Column("fingerprint", sa.String(length=64), nullable=False),
        sa.Column("raw_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("normalized_fingerprint", sa.String(length=64), nullable=True),
        sa.Column("comparison_basis", sa.String(length=32), nullable=False),
        sa.Column("member_count", sa.Integer(), nullable=False),
        sa.Column("pages_json", sa.Text(), nullable=False),
        sa.Column("classification", sa.String(length=64), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_duplicate_groups", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_duplicate_groups_audit_id"), ["audit_id"], unique=False
        )

    op.create_table(
        "structured_data_entities",
        sa.Column("block_id", sa.String(length=64), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("entity_identifier", sa.Text(), nullable=True),
        sa.Column("entity_type", sa.String(length=256), nullable=True),
        sa.Column("properties_json", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_entities", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_entities_audit_id"), ["audit_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_structured_data_entities_block_id"), ["block_id"], unique=False
        )

    op.create_table(
        "structured_data_events",
        sa.Column("event_id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("state", sa.String(length=64), nullable=False),
        sa.Column("affected_count", sa.Integer(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("event_id"),
    )
    with op.batch_alter_table("structured_data_events", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_events_audit_id"), ["audit_id"], unique=False
        )

    op.create_table(
        "structured_data_exports",
        sa.Column("export_format", sa.String(length=64), nullable=False),
        sa.Column("media_type", sa.String(length=128), nullable=False),
        sa.Column("filename", sa.String(length=512), nullable=False),
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=False),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("state", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifact_records.artifact_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("audit_id", "export_format", name="uq_structured_audit_export"),
    )
    with op.batch_alter_table("structured_data_exports", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_exports_audit_id"), ["audit_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_structured_data_exports_artifact_id"),
            ["artifact_id"],
            unique=False,
        )

    op.create_table(
        "structured_data_findings",
        sa.Column("page_url", sa.Text(), nullable=True),
        sa.Column("block_id", sa.String(length=64), nullable=True),
        sa.Column("entity_id", sa.String(length=64), nullable=True),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("evidence_json", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "confidence IN ('high','medium','low','indeterminate')",
            name="ck_structured_finding_confidence",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_findings", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_findings_audit_id"), ["audit_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_structured_data_findings_category"), ["category"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_structured_data_findings_code"), ["code"], unique=False
        )

    op.create_table(
        "structured_data_page_summaries",
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("block_count", sa.Integer(), nullable=False),
        sa.Column("entity_count", sa.Integer(), nullable=False),
        sa.Column("finding_count", sa.Integer(), nullable=False),
        sa.Column("formats_json", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_page_summaries", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_page_summaries_audit_id"), ["audit_id"], unique=False
        )

    op.create_table(
        "structured_data_profiles",
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("profile_name", sa.String(length=128), nullable=False),
        sa.Column("profile_version", sa.String(length=64), nullable=False),
        sa.Column("property_name", sa.String(length=512), nullable=False),
        sa.Column("observation_state", sa.String(length=32), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "observation_state IN "
            "('present','missing','empty','invalid','conflicting','not_applicable','indeterminate')",
            name="ck_structured_profile_state",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_profiles", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_profiles_audit_id"), ["audit_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_structured_data_profiles_entity_id"), ["entity_id"], unique=False
        )

    op.create_table(
        "structured_data_properties",
        sa.Column("entity_id", sa.String(length=64), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("property_name", sa.String(length=512), nullable=False),
        sa.Column("value_json", sa.Text(), nullable=False),
        sa.Column("value_state", sa.String(length=32), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_properties", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_properties_audit_id"), ["audit_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_structured_data_properties_entity_id"), ["entity_id"], unique=False
        )

    op.create_table(
        "structured_data_recommendations",
        sa.Column("action", sa.String(length=128), nullable=False),
        sa.Column("priority", sa.String(length=32), nullable=False),
        sa.Column("confidence", sa.String(length=32), nullable=False),
        sa.Column("requires_human_review", sa.Boolean(), nullable=False),
        sa.Column("scope", sa.String(length=32), nullable=False),
        sa.Column("occurrence_count", sa.Integer(), nullable=False),
        sa.Column("affected_page_count", sa.Integer(), nullable=False),
        sa.Column("supporting_finding_ids_json", sa.Text(), nullable=False),
        sa.Column("supporting_evidence_json", sa.Text(), nullable=False),
        sa.Column("page_url", sa.Text(), nullable=True),
        sa.Column("finding_code", sa.String(length=128), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.CheckConstraint(
            "confidence IN ('high','medium','low','indeterminate')",
            name="ck_structured_recommendation_confidence",
        ),
        sa.CheckConstraint(
            "occurrence_count >= 1", name="ck_structured_recommendation_occurrences"
        ),
        sa.CheckConstraint(
            "affected_page_count >= 0", name="ck_structured_recommendation_affected_pages"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_recommendations", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_recommendations_action"), ["action"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_structured_data_recommendations_audit_id"), ["audit_id"], unique=False
        )

    op.create_table(
        "structured_data_references",
        sa.Column("page_url", sa.Text(), nullable=False),
        sa.Column("source_entity_id", sa.String(length=64), nullable=True),
        sa.Column("target_identifier", sa.Text(), nullable=False),
        sa.Column("resolved", sa.Boolean(), nullable=False),
        sa.Column("id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["audit_id"], ["structured_data_audits.audit_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("structured_data_references", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_structured_data_references_audit_id"), ["audit_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("structured_data_references", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_references_audit_id"))

    op.drop_table("structured_data_references")
    with op.batch_alter_table("structured_data_recommendations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_recommendations_audit_id"))
        batch_op.drop_index(batch_op.f("ix_structured_data_recommendations_action"))

    op.drop_table("structured_data_recommendations")
    with op.batch_alter_table("structured_data_properties", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_properties_entity_id"))
        batch_op.drop_index(batch_op.f("ix_structured_data_properties_audit_id"))

    op.drop_table("structured_data_properties")
    with op.batch_alter_table("structured_data_profiles", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_profiles_entity_id"))
        batch_op.drop_index(batch_op.f("ix_structured_data_profiles_audit_id"))

    op.drop_table("structured_data_profiles")
    with op.batch_alter_table("structured_data_page_summaries", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_page_summaries_audit_id"))

    op.drop_table("structured_data_page_summaries")
    with op.batch_alter_table("structured_data_findings", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_findings_code"))
        batch_op.drop_index(batch_op.f("ix_structured_data_findings_category"))
        batch_op.drop_index(batch_op.f("ix_structured_data_findings_audit_id"))

    op.drop_table("structured_data_findings")
    with op.batch_alter_table("structured_data_exports", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_exports_artifact_id"))
        batch_op.drop_index(batch_op.f("ix_structured_data_exports_audit_id"))

    op.drop_table("structured_data_exports")
    with op.batch_alter_table("structured_data_events", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_events_audit_id"))

    op.drop_table("structured_data_events")
    with op.batch_alter_table("structured_data_entities", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_entities_block_id"))
        batch_op.drop_index(batch_op.f("ix_structured_data_entities_audit_id"))

    op.drop_table("structured_data_entities")
    with op.batch_alter_table("structured_data_duplicate_groups", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_duplicate_groups_audit_id"))

    op.drop_table("structured_data_duplicate_groups")
    with op.batch_alter_table("structured_data_blocks", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_structured_data_blocks_audit_id"))

    op.drop_table("structured_data_blocks")
    with op.batch_alter_table("crawl_structured_data_evidence", schema=None) as batch_op:
        batch_op.drop_index("ix_structured_evidence_run")

    op.drop_table("crawl_structured_data_evidence")
    op.drop_table("structured_data_audits")
    # ### end Alembic commands ###
