"""add Combined Site Audit persistence

Revision ID: 0017_combined_site_audit_persistence
Revises: 0016_site_audit_settings
"""

from collections.abc import Sequence  # noqa: TC003

import sqlalchemy as sa

from alembic import op

revision: str = "0017_combined_site_audit_persistence"
down_revision: str | Sequence[str] | None = "0016_site_audit_settings"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "site_audits",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("audit_name", sa.String(length=200), nullable=False),
        sa.Column("site_label", sa.String(length=200), nullable=True),
        sa.Column("seed_url", sa.Text(), nullable=False),
        sa.Column("normalized_seed_url", sa.Text(), nullable=False),
        sa.Column("lifecycle", sa.String(length=32), nullable=False),
        sa.Column("population_completeness", sa.String(length=32), nullable=False),
        sa.Column("module_completeness", sa.String(length=32), nullable=False),
        sa.Column("partial", sa.Boolean(), nullable=False),
        sa.Column("draft_json", sa.Text(), nullable=False),
        sa.Column("draft_hash", sa.String(length=64), nullable=False),
        sa.Column("created_by", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("failure_explanation", sa.Text(), nullable=True),
        sa.Column("projection_version", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("site_profile_id", sa.String(length=64), nullable=True),
        sa.Column("site_profile_version", sa.Integer(), nullable=True),
        sa.Column("platform_preset_id", sa.String(length=64), nullable=True),
        sa.Column("platform_preset_version", sa.String(length=64), nullable=True),
        sa.Column("parent_job_id", sa.String(length=40), nullable=True),
        sa.Column("parent_run_id", sa.String(length=32), nullable=True),
        sa.CheckConstraint("length(draft_hash) = 64", name="ck_site_audit_draft_hash"),
        sa.CheckConstraint(
            "lifecycle in ('draft','validating','validation_failed','validated',"
            "'preflighting','preflight_failed','ready','queued','running',"
            "'cancel_requested','cancelled','completed','completed_with_warnings',"
            "'partially_completed','failed','recovery_required','archived')",
            name="ck_site_audit_lifecycle",
        ),
        sa.CheckConstraint("revision > 0", name="ck_site_audit_revision_positive"),
        sa.ForeignKeyConstraint(["parent_job_id"], ["jobs.job_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["parent_run_id"], ["runs.run_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    with op.batch_alter_table("site_audits", schema=None) as batch_op:
        batch_op.create_index("ix_site_audits_created", ["created_at", "audit_id"], unique=False)
        batch_op.create_index(
            "ix_site_audits_lifecycle", ["lifecycle", "created_at", "audit_id"], unique=False
        )
        batch_op.create_index(
            "ix_site_audits_seed", ["normalized_seed_url", "created_at", "audit_id"], unique=False
        )

    op.create_table(
        "site_audit_artifact_associations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("artifact_id", sa.String(length=64), nullable=False),
        sa.Column("purpose", sa.String(length=64), nullable=False),
        sa.Column("schema_version", sa.String(length=64), nullable=False),
        sa.Column("completeness", sa.String(length=32), nullable=False),
        sa.Column("row_count", sa.Integer(), nullable=True),
        sa.Column("truncated", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["artifact_id"], ["artifact_records.artifact_id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "audit_id", "artifact_id", "purpose", name="uq_site_audit_artifact_association"
        ),
    )
    with op.batch_alter_table("site_audit_artifact_associations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_artifacts", ["audit_id", "purpose", "id"], unique=False
        )

    op.create_table(
        "site_audit_issue_groups",
        sa.Column("group_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("remediation_key", sa.String(length=128), nullable=False),
        sa.Column("applicable_population", sa.String(length=40), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("affected_url_count", sa.Integer(), nullable=False),
        sa.Column("highest_business_importance", sa.String(length=24), nullable=False),
        sa.Column("pattern_state", sa.String(length=32), nullable=False),
        sa.Column("sitemap_impact", sa.Boolean(), nullable=False),
        sa.Column("metadata_impact", sa.Boolean(), nullable=False),
        sa.Column("indexability_impact", sa.Boolean(), nullable=False),
        sa.Column("internal_link_impact", sa.Boolean(), nullable=False),
        sa.Column("confidence", sa.String(length=24), nullable=False),
        sa.Column("determinacy", sa.String(length=24), nullable=False),
        sa.Column("priority_band", sa.String(length=24), nullable=False),
        sa.Column("priority_key", sa.String(length=256), nullable=False),
        sa.Column("priority_explanation", sa.Text(), nullable=False),
        sa.Column("recommended_action", sa.Text(), nullable=False),
        sa.Column("sample_urls_json", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("projection_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("group_id"),
        sa.UniqueConstraint(
            "audit_id",
            "projection_version",
            "code",
            "remediation_key",
            "applicable_population",
            name="uq_site_audit_issue_group_key",
        ),
    )
    with op.batch_alter_table("site_audit_issue_groups", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_issue_groups_priority",
            ["audit_id", "priority_key", "group_id"],
            unique=False,
        )

    op.create_table(
        "site_audit_module_statuses",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("execution_source", sa.String(length=32), nullable=False),
        sa.Column("specialist_audit_id", sa.String(length=64), nullable=True),
        sa.Column("lifecycle", sa.String(length=32), nullable=False),
        sa.Column("completeness", sa.String(length=32), nullable=False),
        sa.Column("partial", sa.Boolean(), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("failure_explanation", sa.Text(), nullable=True),
        sa.Column("result_count", sa.Integer(), nullable=False),
        sa.Column("artifact_count", sa.Integer(), nullable=False),
        sa.Column("projection_version", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "completeness in ('complete','partial','unavailable','failed','stale','not_enabled')",
            name="ck_site_audit_module_completeness",
        ),
        sa.UniqueConstraint("audit_id", "module", name="uq_site_audit_module_status"),
    )
    with op.batch_alter_table("site_audit_module_statuses", schema=None) as batch_op:
        batch_op.create_index("ix_site_audit_module_statuses", ["audit_id", "module"], unique=False)

    op.create_table(
        "site_audit_snapshots",
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("source_revision", sa.Integer(), nullable=False),
        sa.Column("canonical_json", sa.Text(), nullable=False),
        sa.Column("sha256", sa.String(length=64), nullable=False),
        sa.Column("approved_hosts_json", sa.Text(), nullable=False),
        sa.Column("scope_policy_json", sa.Text(), nullable=False),
        sa.Column("crawl_limits_json", sa.Text(), nullable=False),
        sa.Column("thresholds_json", sa.Text(), nullable=False),
        sa.Column("enabled_modules_json", sa.Text(), nullable=False),
        sa.Column("tracking_parameters_json", sa.Text(), nullable=False),
        sa.Column("population_definition_version", sa.String(length=64), nullable=False),
        sa.Column("priority_model_version", sa.String(length=64), nullable=False),
        sa.Column("artifact_schema_versions_json", sa.Text(), nullable=False),
        sa.Column("application_version", sa.String(length=64), nullable=False),
        sa.Column("projection_version", sa.String(length=64), nullable=False),
        sa.Column("site_profile_id", sa.String(length=64), nullable=True),
        sa.Column("site_profile_version", sa.Integer(), nullable=True),
        sa.Column("platform_preset_id", sa.String(length=64), nullable=True),
        sa.Column("platform_preset_version", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("length(sha256) = 64", name="ck_site_audit_snapshot_hash"),
        sa.CheckConstraint("source_revision > 0", name="ck_site_audit_snapshot_revision"),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("snapshot_id"),
        sa.UniqueConstraint("audit_id"),
    )
    with op.batch_alter_table("site_audit_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_snapshots_audit", ["audit_id", "created_at"], unique=False
        )

    op.create_table(
        "site_audit_summary_projections",
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("urls_discovered", sa.Integer(), nullable=False),
        sa.Column("urls_enqueued", sa.Integer(), nullable=False),
        sa.Column("urls_fetched", sa.Integer(), nullable=False),
        sa.Column("html_urls", sa.Integer(), nullable=False),
        sa.Column("indexable_urls", sa.Integer(), nullable=False),
        sa.Column("canonical_urls", sa.Integer(), nullable=False),
        sa.Column("metadata_scoring_eligible_urls", sa.Integer(), nullable=False),
        sa.Column("sitemap_eligible_urls", sa.Integer(), nullable=False),
        sa.Column("urls_excluded", sa.Integer(), nullable=False),
        sa.Column("partial_urls", sa.Integer(), nullable=False),
        sa.Column("failed_urls", sa.Integer(), nullable=False),
        sa.Column("indeterminate_urls", sa.Integer(), nullable=False),
        sa.Column("critical_issue_groups", sa.Integer(), nullable=False),
        sa.Column("high_issue_groups", sa.Integer(), nullable=False),
        sa.Column("medium_issue_groups", sa.Integer(), nullable=False),
        sa.Column("low_issue_groups", sa.Integer(), nullable=False),
        sa.Column("unassigned_issue_groups", sa.Integer(), nullable=False),
        sa.Column("recommendation_include", sa.Integer(), nullable=False),
        sa.Column("recommendation_exclude", sa.Integer(), nullable=False),
        sa.Column("recommendation_review", sa.Integer(), nullable=False),
        sa.Column("recommendation_indeterminate", sa.Integer(), nullable=False),
        sa.Column("image_summary_json", sa.Text(), nullable=False),
        sa.Column("structured_data_summary_json", sa.Text(), nullable=False),
        sa.Column("module_counts_json", sa.Text(), nullable=False),
        sa.Column("projection_version", sa.String(length=64), nullable=False),
        sa.Column("revision", sa.Integer(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("revision > 0", name="ck_site_audit_summary_revision"),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("audit_id"),
    )
    op.create_table(
        "site_audit_urls",
        sa.Column("url_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("original_url", sa.Text(), nullable=False),
        sa.Column("requested_url", sa.Text(), nullable=False),
        sa.Column("normalized_url", sa.Text(), nullable=False),
        sa.Column("normalized_url_identity", sa.String(length=64), nullable=False),
        sa.Column("final_url", sa.Text(), nullable=True),
        sa.Column("host", sa.String(length=253), nullable=False),
        sa.Column("path", sa.Text(), nullable=False),
        sa.Column("query", sa.Text(), nullable=False),
        sa.Column("discovery_state", sa.String(length=32), nullable=False),
        sa.Column("enqueued_state", sa.String(length=32), nullable=False),
        sa.Column("fetch_state", sa.String(length=32), nullable=False),
        sa.Column("parse_state", sa.String(length=32), nullable=False),
        sa.Column("http_status", sa.Integer(), nullable=True),
        sa.Column("content_type", sa.String(length=256), nullable=True),
        sa.Column("fetch_outcome", sa.String(length=64), nullable=True),
        sa.Column("redirect_state", sa.String(length=32), nullable=False),
        sa.Column("robots_state", sa.String(length=32), nullable=False),
        sa.Column("indexability_state", sa.String(length=32), nullable=False),
        sa.Column("canonical_state", sa.String(length=32), nullable=False),
        sa.Column("existing_sitemap_state", sa.String(length=32), nullable=False),
        sa.Column("recommended_sitemap_state", sa.String(length=32), nullable=False),
        sa.Column("discovery_decision", sa.String(length=64), nullable=False),
        sa.Column("metadata_scoring_decision", sa.String(length=64), nullable=False),
        sa.Column("sitemap_policy_decision", sa.String(length=64), nullable=False),
        sa.Column("highest_severity", sa.String(length=24), nullable=True),
        sa.Column("issue_count", sa.Integer(), nullable=False),
        sa.Column("crawl_depth", sa.Integer(), nullable=True),
        sa.Column("inbound_link_count", sa.Integer(), nullable=False),
        sa.Column("outbound_link_count", sa.Integer(), nullable=False),
        sa.Column("partial", sa.Boolean(), nullable=False),
        sa.Column("failure_code", sa.String(length=128), nullable=True),
        sa.Column("business_importance", sa.String(length=24), nullable=False),
        sa.Column("evidence_id", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "http_status IS NULL OR (http_status >= 100 AND http_status <= 599)",
            name="ck_site_audit_url_http_status",
        ),
        sa.CheckConstraint(
            "length(normalized_url_identity) = 64",
            name="ck_site_audit_url_identity_hash",
        ),
        sa.CheckConstraint("sequence >= 0", name="ck_site_audit_url_sequence"),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("url_id"),
        sa.UniqueConstraint(
            "audit_id", "normalized_url_identity", name="uq_site_audit_url_identity"
        ),
        sa.UniqueConstraint("audit_id", "sequence", name="uq_site_audit_url_sequence"),
    )
    with op.batch_alter_table("site_audit_urls", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_urls_order", ["audit_id", "sequence", "url_id"], unique=False
        )
        batch_op.create_index(
            "ix_site_audit_urls_severity",
            ["audit_id", "highest_severity", "sequence"],
            unique=False,
        )
        batch_op.create_index(
            "ix_site_audit_urls_sitemap",
            ["audit_id", "recommended_sitemap_state", "sequence"],
            unique=False,
        )
        batch_op.create_index(
            "ix_site_audit_urls_status", ["audit_id", "http_status", "sequence"], unique=False
        )

    op.create_table(
        "site_audit_disabled_inherited_rules",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("stable_rule_id", sa.String(length=96), nullable=False),
        sa.Column("rule_source", sa.String(length=32), nullable=False),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["site_audit_snapshots.snapshot_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("snapshot_id", "stable_rule_id", name="uq_site_audit_disabled_rule"),
    )
    with op.batch_alter_table("site_audit_disabled_inherited_rules", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_disabled_rules", ["audit_id", "stable_rule_id"], unique=False
        )

    op.create_table(
        "site_audit_findings",
        sa.Column("finding_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("url_id", sa.String(length=64), nullable=True),
        sa.Column("module", sa.String(length=64), nullable=False),
        sa.Column("category", sa.String(length=64), nullable=False),
        sa.Column("code", sa.String(length=128), nullable=False),
        sa.Column("severity", sa.String(length=24), nullable=False),
        sa.Column("determinacy", sa.String(length=24), nullable=False),
        sa.Column("confidence", sa.String(length=24), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("evidence_reference", sa.String(length=128), nullable=True),
        sa.Column("sitemap_impact", sa.Boolean(), nullable=False),
        sa.Column("metadata_impact", sa.Boolean(), nullable=False),
        sa.Column("indexability_impact", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("projection_version", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["url_id"], ["site_audit_urls.url_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("finding_id"),
    )
    with op.batch_alter_table("site_audit_findings", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_findings", ["audit_id", "module", "severity", "finding_id"], unique=False
        )

    op.create_table(
        "site_audit_rule_snapshots",
        sa.Column("snapshot_rule_id", sa.String(length=96), nullable=False),
        sa.Column("snapshot_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("stable_rule_id", sa.String(length=96), nullable=False),
        sa.Column("rule_source", sa.String(length=32), nullable=False),
        sa.Column("source_id", sa.String(length=64), nullable=True),
        sa.Column("source_version", sa.String(length=64), nullable=False),
        sa.Column("decision_layer", sa.String(length=32), nullable=False),
        sa.Column("match_type", sa.String(length=40), nullable=False),
        sa.Column("match_value", sa.Text(), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("specificity", sa.Integer(), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("overrides_rule_ids_json", sa.Text(), nullable=False),
        sa.Column("stable_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["snapshot_id"], ["site_audit_snapshots.snapshot_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("snapshot_rule_id"),
        sa.UniqueConstraint("snapshot_id", "stable_rule_id", name="uq_site_audit_snapshot_rule"),
    )
    with op.batch_alter_table("site_audit_rule_snapshots", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_rules_order",
            ["audit_id", "decision_layer", "stable_order"],
            unique=False,
        )

    op.create_table(
        "site_audit_url_discovery_sources",
        sa.Column("discovery_id", sa.String(length=64), nullable=False),
        sa.Column("url_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=40), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("source_artifact_id", sa.String(length=64), nullable=True),
        sa.Column("source_evidence_id", sa.String(length=64), nullable=True),
        sa.Column("discovered_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("original_observed_url", sa.Text(), nullable=False),
        sa.Column("relationship_json", sa.Text(), nullable=False),
        sa.Column("evidence_key", sa.String(length=64), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["url_id"], ["site_audit_urls.url_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("discovery_id"),
        sa.UniqueConstraint("audit_id", "sequence", name="uq_site_audit_discovery_sequence"),
        sa.UniqueConstraint("url_id", "evidence_key", name="uq_site_audit_discovery_evidence"),
    )
    with op.batch_alter_table("site_audit_url_discovery_sources", schema=None) as batch_op:
        batch_op.create_index("ix_site_audit_discoveries_url", ["url_id", "sequence"], unique=False)

    op.create_table(
        "site_audit_url_populations",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("url_id", sa.String(length=64), nullable=False),
        sa.Column("population", sa.String(length=40), nullable=False),
        sa.Column("decision_state", sa.String(length=32), nullable=False),
        sa.Column("reason_code", sa.String(length=128), nullable=True),
        sa.Column("evidence_id", sa.String(length=64), nullable=True),
        sa.Column("definition_version", sa.String(length=64), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["url_id"], ["site_audit_urls.url_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.CheckConstraint(
            "population in ('discovered','enqueued','fetched','parsed_html','indexable',"
            "'canonical','metadata_scoring_eligible','sitemap_eligible','resource',"
            "'excluded','partial','failed','indeterminate')",
            name="ck_site_audit_population",
        ),
        sa.UniqueConstraint("url_id", "population", name="uq_site_audit_url_population"),
    )
    with op.batch_alter_table("site_audit_url_populations", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_populations", ["audit_id", "population", "url_id"], unique=False
        )

    op.create_table(
        "site_audit_issue_group_memberships",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("group_id", sa.String(length=64), nullable=False),
        sa.Column("finding_id", sa.String(length=64), nullable=False),
        sa.Column("url_id", sa.String(length=64), nullable=True),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("membership_reason", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["finding_id"], ["site_audit_findings.finding_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["group_id"], ["site_audit_issue_groups.group_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["url_id"], ["site_audit_urls.url_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("group_id", "finding_id", name="uq_site_audit_issue_membership"),
        sa.UniqueConstraint("group_id", "sequence", name="uq_site_audit_issue_membership_sequence"),
    )
    with op.batch_alter_table("site_audit_issue_group_memberships", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_memberships_order", ["group_id", "sequence", "id"], unique=False
        )

    op.create_table(
        "site_audit_rule_matches",
        sa.Column("match_id", sa.String(length=64), nullable=False),
        sa.Column("audit_id", sa.String(length=64), nullable=False),
        sa.Column("url_id", sa.String(length=64), nullable=False),
        sa.Column("snapshot_rule_id", sa.String(length=96), nullable=False),
        sa.Column("decision_layer", sa.String(length=32), nullable=False),
        sa.Column("primary_rule", sa.Boolean(), nullable=False),
        sa.Column("contributed", sa.Boolean(), nullable=False),
        sa.Column("disabled", sa.Boolean(), nullable=False),
        sa.Column("overridden", sa.Boolean(), nullable=False),
        sa.Column("specificity", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("precedence_key", sa.String(length=200), nullable=False),
        sa.Column("conflict_code", sa.String(length=128), nullable=True),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column("matched_original_url", sa.Text(), nullable=False),
        sa.Column("matched_normalized_url", sa.Text(), nullable=False),
        sa.Column("matched_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["audit_id"], ["site_audits.audit_id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["snapshot_rule_id"], ["site_audit_rule_snapshots.snapshot_rule_id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["url_id"], ["site_audit_urls.url_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("match_id"),
        sa.UniqueConstraint(
            "url_id", "snapshot_rule_id", "decision_layer", name="uq_site_audit_rule_match"
        ),
    )
    with op.batch_alter_table("site_audit_rule_matches", schema=None) as batch_op:
        batch_op.create_index(
            "ix_site_audit_rule_matches_order",
            ["audit_id", "url_id", "decision_layer", "precedence_key", "match_id"],
            unique=False,
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("site_audit_rule_matches", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_rule_matches_order")

    op.drop_table("site_audit_rule_matches")
    with op.batch_alter_table("site_audit_issue_group_memberships", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_memberships_order")

    op.drop_table("site_audit_issue_group_memberships")
    with op.batch_alter_table("site_audit_url_populations", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_populations")

    op.drop_table("site_audit_url_populations")
    with op.batch_alter_table("site_audit_url_discovery_sources", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_discoveries_url")

    op.drop_table("site_audit_url_discovery_sources")
    with op.batch_alter_table("site_audit_rule_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_rules_order")

    op.drop_table("site_audit_rule_snapshots")
    with op.batch_alter_table("site_audit_findings", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_findings")

    op.drop_table("site_audit_findings")
    with op.batch_alter_table("site_audit_disabled_inherited_rules", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_disabled_rules")

    op.drop_table("site_audit_disabled_inherited_rules")
    with op.batch_alter_table("site_audit_urls", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_urls_status")
        batch_op.drop_index("ix_site_audit_urls_sitemap")
        batch_op.drop_index("ix_site_audit_urls_severity")
        batch_op.drop_index("ix_site_audit_urls_order")

    op.drop_table("site_audit_urls")
    op.drop_table("site_audit_summary_projections")
    with op.batch_alter_table("site_audit_snapshots", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_snapshots_audit")

    op.drop_table("site_audit_snapshots")
    with op.batch_alter_table("site_audit_module_statuses", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_module_statuses")

    op.drop_table("site_audit_module_statuses")
    with op.batch_alter_table("site_audit_issue_groups", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_issue_groups_priority")

    op.drop_table("site_audit_issue_groups")
    with op.batch_alter_table("site_audit_artifact_associations", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audit_artifacts")

    op.drop_table("site_audit_artifact_associations")
    with op.batch_alter_table("site_audits", schema=None) as batch_op:
        batch_op.drop_index("ix_site_audits_seed")
        batch_op.drop_index("ix_site_audits_lifecycle")
        batch_op.drop_index("ix_site_audits_created")

    op.drop_table("site_audits")
    # ### end Alembic commands ###
